# name of the workflow
name: My Action

# define the trigger for the workflow
on: [push]
# on:
#   # trigger the workflow on push events
#   push:
#     # only trigger the workflow on the master branch
#     branches: [ master ]
#   # trigger the workflow on pull request events
#   pull_request:
#     # only trigger the workflow on the master branch
#     branches: [ master ]

# define the jobs that will run in the workflow
jobs:

  # job to print something
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Actions!"

  build-and-test:
    needs: [say-hello] #second job needs another job to be completed
    runs-on: ubuntu-latest
    steps:
      # use https://github.com/actions/checkout to checkout the repository
      - name: Checkout this repo
        uses: actions/checkout@v3

      # install necessary dependencies
      - name: Install dependencies
        run: sudo apt install -y build-essential python3 #run commands in the shell

      # see where we are
      - run: pwd

      # run our tests
      - name: Run tests
        run: python3 test.py
